
export const BLITPUNK_CANVAS_ELEMENT = 'blitpunk-canvas'
export const BLITPUNK_SCENE_ELEMENT = 'blitpunk-scene'
export const BLITPUNK_TEXTURE_ATLAS_ELEMENT = 'blitpunk-texture-atlas'
export const BLITPUNK_SPRITE_GROUP_ELEMENT = 'blitpunk-sprite-group'

export const BLITPUNK_CANVAS_NODE_NAME = BLITPUNK_CANVAS_ELEMENT.toUpperCase()
export const BLITPUNK_SCENE_NODE_NAME = BLITPUNK_SCENE_ELEMENT.toUpperCase()
export const BLITPUNK_TEXTURE_ATLAS_NODE_NAME = BLITPUNK_TEXTURE_ATLAS_ELEMENT.toUpperCase()
export const BLITPUNK_SPRITE_GROUP_NODE_NAME = BLITPUNK_SPRITE_GROUP_ELEMENT.toUpperCase()

export const COMPONENT_RENDER_PRIO_PROJECTION = 1000
export const COMPONENT_RENDER_PRIO_CHILDREN = 10
