
export const BLITPUNK_CANVAS_ELEMENT = 'blitpunk-canvas'
export const BLITPUNK_SCENE_ELEMENT = 'blitpunk-scene'

export const BLITPUNK_CANVAS_NODE_NAME = BLITPUNK_CANVAS_ELEMENT.toUpperCase()
export const BLITPUNK_SCENE_NODE_NAME = BLITPUNK_SCENE_ELEMENT.toUpperCase()

export const COMPONENT_RENDER_PRIO_PROJECTION = 1000
export const COMPONENT_RENDER_PRIO_CHILDREN = 10
