/* eslint no-multi-spaces: ["error", { exceptions: { "VariableDeclarator": true } }] */

export const HTML_ELEMENT_ENTITY        = 'blitpunk-entity'
export const HTML_ELEMENT_CANVAS        = 'blitpunk-canvas'
export const HTML_ELEMENT_SPRITE_GROUP  = 'blitpunk-sprite-group'
export const HTML_ELEMENT_TEXTURE_ATLAS = 'blitpunk-texture-atlas'

export const ATTR_ALPHA               = 'alpha'
export const ATTR_ANTIALIAS           = 'antialias'
export const ATTR_BLEND_MODE          = 'blend-mode'
export const ATTR_CAPACITY            = 'vo-capacity'
export const ATTR_CLEAR_COLOR         = 'clear-color'
export const ATTR_DEPTH               = 'depth'
export const ATTR_DESCRIPTOR          = 'vo-descriptor'
export const ATTR_FLIP_Y              = 'flip-y'
export const ATTR_FRAGMENT_SHADER     = 'fragment-shader'
export const ATTR_MODULE_SRC          = 'module-src'
export const ATTR_NEAREST             = 'nearest'
export const ATTR_PREMULTIPLIED_ALPHA = 'premultiplied-alpha'
export const ATTR_PREMULTIPLY_ALPHA   = 'premultiply-alpha'
export const ATTR_PRESERVE_DRAW       = 'preserve-drawing-buffer'
export const ATTR_PRIMITIVE           = 'primitive-type'
export const ATTR_PROJECTION          = 'projection'
export const ATTR_REPEATABLE          = 'repeatable'
export const ATTR_SRC                 = 'src'
export const ATTR_STENCIL             = 'stencil'
export const ATTR_TEXTURE_MAP         = 'texture-map'
export const ATTR_VERTEX_SHADER       = 'vertex-shader'
export const ATTR_VO_NEW              = 'vo-new'
export const ATTR_VO_ZERO             = 'vo-zero'
