name: CI

on: [push]

jobs:
  run_tests:
    name: build and run tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: install
      run: yarn install
    - name: build
      run: yarn build
    - name: lint
      run: yarn lint
    - name: test
      run: yarn test
